version: "3.9"

services:
    fin_api:
        image: postgres
        container_name: fin_api
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=vitor123
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=fin_api
        volumes:
            - pgdata:/data/postgres
volumes:
    pgdata:
        driver: local
